### PR TITLE
chore(metadata): Point to docs.rs, to repository and more accurate de…

### PR DESCRIPTION
**Pull request by badboy**
…scription

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 6b7e332 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 6b7e332 with merge 52ae4e8...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/lzf-rs/builds/171683754)
Approved by: badboy
Pushing 52ae4e8bce5841840d0d09f449d41b7f298098fe to master...

**Pull request merged**
