### PR TITLE
test: Move quickcheck to dev-dependencies

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 48dd86c has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 48dd86c with merge d0516d6...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/lzf-rs/builds/130104873)

**Pull request merged**
