### PR TITLE
chore(CI): Reorder rust targets on Travis

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit cae5ae5 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit cae5ae5 with merge 7bbac59...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/lzf-rs/builds/171676771)
Approved by: badboy
Pushing 7bbac5983cc155ffd758ed425720792b2b6516e6 to master...

**Pull request merged**
