### PR TITLE
Less unsafe

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 28abb4a has been approved by `badboy`

**Comment by badboy** [comment]
@not-a-robot p=1

**Comment by ghost** [comment]
:hourglass: Testing commit 28abb4a with merge 1c3992d...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/lzf-rs/builds/171681066)
Approved by: badboy
Pushing 1c3992d76fd797bfca35fbd5656b78743211b9ed to master...

**Pull request merged**
