### PR TITLE
With buffer

### PR DESCRIPTION
**Pull request by badboy**
BREAKING CHANGE: This changes the API, making the user of the API
                 responsible to create a large enough buffer to decompress the given
                 data.

### CODE REVIEW

**Comment by badboy** [comment]
bors try

**Comment by badboy** [comment]
bors try

**Comment by newpavlov** [comment]
Hi! Do you plan to merge this?

BTW IIUC if you'll add output buffer as an argument to `compress` function as well you can make this crate `no_std` capable (i.e. suitable for embedded development). For convenience you can add a separate method which will be generic over `Write` trait.

**Comment by badboy** [comment]
I haven't touched that code in quite a while. Are you using lzf-rs in any form?
Giving it a brief look I see some small unsafe things that should be fixed first.

**Comment by newpavlov** [comment]
I plan to use it for [PCD](http://pointclouds.org/documentation/tutorials/pcd_file_format.php) format decoder. LZF is used in it for not listed on the page `binary_compressed` variant.

BTW I think it could be worth to remove C code from this repo and leave only test vectors. Initially I was a bit confused and thought that this crate wraps C lib.

**Comment by badboy** [comment]
Initially it was a wrapper around the C code. The C code is still used for [compatibility checks on CI](https://github.com/badboy/lzf-rs/blob/master/.travis.yml#L28) and I intend to keep that.

I'll give it another look and see if I can merge this.

**Comment by mulimoen** [comment]
Any progress on this? We might be looking at using this code in `hdf5-rust` if we have a function that takes slices.

**Comment by badboy** [comment]
Haven't worked on this in .... I guess somewhere between 2 1/2 and 4 years.
It definitely needs some work (look at all that unsafety and use of `mem::uninitialized`)
I won't have time anytime soon to fix that or pick up this PR again.

If you want to use it I would recommend picking up the code again, I then might be able to squeeze in a review.

**Pull request closed without merging**
