### PR TITLE
Quickcheck

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit bbe1010 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit bbe1010 with merge 86edb84...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/lzf-rs/builds/129946040)

**Pull request merged**
